<?php

declare(strict_types=1);

namespace Phosagro\Object;

final class Participant
{
    public readonly bool $rejected;

    public function __construct(
        public readonly string $autogeneratedCode,
        public readonly string $autogeneratedName,
        public readonly bool $came,
        public readonly bool $confirmed,
        public readonly int $eventIdentifier,
        public readonly int $participantIdentifier,
        public readonly bool $preventConfirmationEmail,
        public readonly bool $preventRejectionEmail,
        public readonly bool $refused,
        public readonly string $rejectionReason,
        public readonly int $userIdentifier,
    ) {
        $this->rejected = ('' !== $rejectionReason);
    }

    public function __toString(): string
    {
        return sprintf('[%d] %s', $this->participantIdentifier, $this->autogeneratedName);
    }

    public static function getName(): string
    {
        return GetMessage(self::class);
    }

    public function toApi(): array
    {
        return [
            'confirmed' => $this->confirmed,
            'rejected' => $this->rejected,
        ];
    }
}
